#pragma kernel ColourGaussians
#pragma kernel FinalizeColours
#pragma kernel WriteDepth
#pragma kernel ConvertDepth
#pragma kernel ClearDepth

Texture2D<float4> _ColorTex;
SamplerState sampler_ColorTex;

RWTexture2D<int> DepthTexture; // WriteDepth kernel writes here

Texture2D<float> _DepthTex;
//Texture2D<float> _DA3DepthTex;

StructuredBuffer<float3> _Positions;

RWStructuredBuffer<float4> _FinalColor;
RWStructuredBuffer<float4> _AccumColor;
RWStructuredBuffer<uint> _Contribution;
RWStructuredBuffer<float> _BestCameraScore;

RWStructuredBuffer<float4> _DebugBuffer;

uint TextureWidth;
uint TextureHeight;

uint ColorTextureWidth;
uint ColorTextureHeight;

float4x4 _ViewProj;
float4x4 _WorldToCamera;

int _GaussianCount;

Texture2D<int> DepthIntTexture;
RWTexture2D<float> DepthFloatTexture;


[numthreads(256, 1, 1)]
void ColourGaussians(uint id : SV_DispatchThreadID)
{
    if (id >= _GaussianCount)
        return;


    float3 worldPos = _Positions[id];

    
    float4 camPos = mul(_WorldToCamera, float4(worldPos, 1));
    float gaussianDepth = -camPos.z;
    
    if (gaussianDepth <= 0)
        return;
    
    float4 clip = mul(
        _ViewProj,
        float4(worldPos, 1)
    );


    if (clip.w <= 0)
        return;


    float2 ndc = clip.xy / clip.w;


    float2 uv;

    uv.x = 1.0 - (ndc.x * 0.5 + 0.5);
    uv.y = 1.0 - (ndc.y * 0.5 + 0.5);


    if (uv.x < 0 || uv.x > 1 ||
        uv.y < 0 || uv.y > 1)
    {
        return;
    }
    
    
    uint2 pixel;

    pixel.x = uv.x * TextureWidth;
    pixel.y = uv.y * TextureHeight;
    
    if (pixel.x >= TextureWidth - 1 ||
    pixel.y >= TextureHeight - 1)
    {
        return;
    }
    
    uint2 colorPixel;

    colorPixel.x = uv.x * ColorTextureWidth;
    colorPixel.y = (1.0 - uv.y) * ColorTextureHeight;

    colorPixel.x = min(colorPixel.x, ColorTextureWidth - 1);
    colorPixel.y = min(colorPixel.y, ColorTextureHeight - 1);

    float4 color = _ColorTex.Load(int3(colorPixel, 0));

    if (color.a <= 0.0)
    {
        return;
    }    

    
    const int depthRadius = 1;

    float depthFromMap = 9999.0;

    for (int y = -depthRadius; y <= depthRadius; y++)
    {
        for (int x = -depthRadius; x <= depthRadius; x++)
        {
            int2 p = int2(pixel) + int2(x, y);

            if (p.x < 0 || p.y < 0 ||
            p.x >= TextureWidth ||
            p.y >= TextureHeight)
            {
                continue;
            }

            float d = _DepthTex.Load(int3(p, 0));

            if (d > 0.001 && d < depthFromMap)
            {
                depthFromMap = d;
            }
        }
    }
    if (depthFromMap <= 0.001 || depthFromMap >= 9990.0)
    {
        return;
    }
    
    const float frontTolerance = 0.02;
    const float backTolerance = 0.03;

    float delta = gaussianDepth - depthFromMap;

    
    if (delta < -frontTolerance || delta > backTolerance)
    {
        return;
    }
   
    if (id < 10)
    {
        _DebugBuffer[0] = float4(
            gaussianDepth,
            depthFromMap,
             gaussianDepth - depthFromMap,
            0);

        _DebugBuffer[1] = float4(
            uv.x,
            uv.y,
            pixel.x,
            pixel.y
        );
        
        
        _DebugBuffer[2] = float4(
            TextureWidth,
            TextureHeight,
            ColorTextureWidth,
            ColorTextureHeight
        );
    }
    
    float depthError = abs(delta);

    // Distance from image centre (0 = centre, ~1.4 = corner)
    float2 centred = uv * 2.0 - 1.0;
    float radial = length(centred);

    // Distance from nearest image edge
    float border = min(
        min(uv.x, uv.y),
        min(1.0 - uv.x, 1.0 - uv.y)
    );

    // Lower score is better
    float score =
      depthError * 150.0
    + radial * 3.0
    + (1.0 - border) * 2.0;

    // Only replace the current camera if it's noticeably better
    if (score < _BestCameraScore[id] - 0.1)
    {
        _BestCameraScore[id] = score;
        _AccumColor[id] = color;
        _Contribution[id] = 1;
    }
}


[numthreads(256, 1, 1)]
void FinalizeColours(uint id : SV_DispatchThreadID)
{
    if (id >= _GaussianCount)
        return;


    uint count = _Contribution[id];


    if (count == 0)
    {
        _FinalColor[id] = float4(0, 0, 0, 0);
        return;
    }
    else
    {
        float4 color = _AccumColor[id] / count;
        color.a = 1;
        _FinalColor[id] = color;
    }
}

[numthreads(64, 1, 1)]
void WriteDepth(uint id : SV_DispatchThreadID)
{
    if (id >= _GaussianCount)
        return;


    float3 worldPos = _Positions[id];


    float4 camPos = mul(
        _WorldToCamera,
        float4(worldPos, 1)
    );


    float depth = -camPos.z;


    if (depth <= 0)
        return;


    float4 clipPos = mul(
        _ViewProj,
        float4(worldPos, 1)
    );


    float2 ndc = clipPos.xy / clipPos.w;


    float2 uv;


    uv.x = 1.0 - (ndc.x * 0.5 + 0.5);
    uv.y = 1.0 - (ndc.y * 0.5 + 0.5);


    if (uv.x < 0 || uv.x > 1 ||
        uv.y < 0 || uv.y > 1)
    {
        return;
    }


    // ------------------------------------------
    // Check colour alpha mask
    // ------------------------------------------

    uint2 colorPixel;


    colorPixel.x = (uint) (uv.x * ColorTextureWidth);
    colorPixel.y = (uint) ((1.0 - uv.y) * ColorTextureHeight);


    colorPixel.x = min(
        colorPixel.x,
        ColorTextureWidth - 1
    );


    colorPixel.y = min(
        colorPixel.y,
        ColorTextureHeight - 1
    );


    float4 color = _ColorTex.Load(
        int3(colorPixel, 0)
    );


    // Background pixel -> ignore this Gaussian
    if (color.a <= 0.0)
    {
        return;
    }


    // ------------------------------------------
    // Write depth
    // ------------------------------------------

    uint2 pixel;


    pixel.x = (uint) (uv.x * TextureWidth);
    pixel.y = (uint) (uv.y * TextureHeight);


    if (pixel.x >= TextureWidth ||
        pixel.y >= TextureHeight)
    {
        return;
    }


    int depthInt = (int) (depth * 1000.0);


    const int radius = 2;


    for (int y = -radius; y <= radius; y++)
    {
        for (int x = -radius; x <= radius; x++)
        {

            if (x * x + y * y > radius * radius)
                continue;


            int2 p = int2(pixel) + int2(x, y);


            if (p.x < 0 || p.y < 0 ||
                p.x >= TextureWidth ||
                p.y >= TextureHeight)
            {
                continue;
            }


            int oldDepth;


            InterlockedMin(
                DepthTexture[p],
                depthInt,
                oldDepth
            );
        }
    }
}

[numthreads(8, 8, 1)]
void ConvertDepth(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= TextureWidth ||
       id.y >= TextureHeight)
        return;


    int d = DepthIntTexture[id.xy];

    if (d == 2147483647)
    {
        DepthFloatTexture[id.xy] = 9999;
    }
    else
    {
        DepthFloatTexture[id.xy] = d / 1000.0;
    }
}

[numthreads(8, 8, 1)]
void ClearDepth(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= TextureWidth ||
       id.y >= TextureHeight)
        return;

    DepthTexture[id.xy] = 2147483647;
}
